export const actionType = {
    ADD_ADDRESS : 'ADD_ADDRESS',
    ADD_BEDROOM : 'ADD_BEDROOM',
    ADD_BATHROOM : 'ADD_BATHROOM',
    ADD_DESCRIPTION : 'ADD_DESCRIPTION',
    ADD_IMAGES : 'ADD_IMAGES',
    ADD_FEATURED_IMG : 'ADD_FEATURED_IMG',
    IMG_UPLOADED : 'IMG_UPLOADED',
    LIMIT_EXCEED : 'LIMIT_EXCEED'
     
}